export const NOTIFICATION_TYPE = {
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_ACCEPTED: 'BOOKING_ACCEPTED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',

  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',

  COMMENT_CREATED: 'COMMENT_CREATED',

  ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  ACCOUNT_UNBLOCKED: 'ACCOUNT_UNBLOCKED',

  PASSWORD_RESET: 'PASSWORD_RESET',

  SYSTEM: 'SYSTEM',
} as const;
